# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='Auto',
            new_name='auto',
        ),
    ]
