# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_20181212_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
