# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_auto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='descueto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
