# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0005_auto_20181213_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
