# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0006_factura_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='descueto',
            new_name='descuento',
        ),
    ]
